"""initial migrations

Revision ID: 3764cf2a6992
Revises:
Create Date: 2025-10-24 22:34:58.820592

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3764cf2a6992"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "faculties",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("uuid", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "last_modified",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("display_name"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_faculties_created_at"), "faculties", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_faculties_last_modified"), "faculties", ["last_modified"], unique=False
    )
    op.create_table(
        "groups",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("uuid", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "last_modified",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_groups_created_at"), "groups", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_groups_last_modified"), "groups", ["last_modified"], unique=False
    )
    op.create_table(
        "permissions",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("uuid", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "last_modified",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_permissions_created_at"), "permissions", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_permissions_last_modified"),
        "permissions",
        ["last_modified"],
        unique=False,
    )
    op.create_table(
        "roles",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("uuid", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "last_modified",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_roles_created_at"), "roles", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_roles_last_modified"), "roles", ["last_modified"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("old_password_hash", sa.String(length=255), nullable=True),
        sa.Column("temp_password_hash", sa.String(length=255), nullable=True),
        sa.Column("firstname", sa.String(length=255), nullable=False),
        sa.Column("lastname", sa.String(length=255), nullable=False),
        sa.Column("middlename", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_admin", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("can_login", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("is_temp_email", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("is_temp_phone", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("uuid", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "last_modified",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("phone"),
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_users_last_modified"), "users", ["last_modified"], unique=False
    )
    op.create_table(
        "departments",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("faculty_id", sa.String(length=45), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("uuid", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "last_modified",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["faculty_id"], ["faculties.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("display_name"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_departments_created_at"), "departments", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_departments_last_modified"),
        "departments",
        ["last_modified"],
        unique=False,
    )
    op.create_table(
        "permission_role",
        sa.Column("permission_id", sa.String(length=50), nullable=True),
        sa.Column("role_id", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.uuid"],
        ),
    )
    op.create_table(
        "role_group",
        sa.Column("role_id", sa.String(length=50), nullable=True),
        sa.Column("group_id", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.uuid"],
        ),
    )
    op.create_table(
        "user_group",
        sa.Column("group_id", sa.String(length=50), nullable=True),
        sa.Column("user_id", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.uuid"],
        ),
    )
    op.create_table(
        "programmes",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("department_id", sa.String(length=45), nullable=False),
        sa.Column("faculty_id", sa.String(length=45), nullable=False),
        sa.Column("code", sa.String(length=8), nullable=True),
        sa.Column("prefix_code", sa.String(length=8), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("uuid", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "last_modified",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["department_id"], ["departments.uuid"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["faculty_id"], ["faculties.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_programmes_created_at"), "programmes", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_programmes_last_modified"),
        "programmes",
        ["last_modified"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_programmes_last_modified"), table_name="programmes")
    op.drop_index(op.f("ix_programmes_created_at"), table_name="programmes")
    op.drop_table("programmes")
    op.drop_table("user_group")
    op.drop_table("role_group")
    op.drop_table("permission_role")
    op.drop_index(op.f("ix_departments_last_modified"), table_name="departments")
    op.drop_index(op.f("ix_departments_created_at"), table_name="departments")
    op.drop_table("departments")
    op.drop_index(op.f("ix_users_last_modified"), table_name="users")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_roles_last_modified"), table_name="roles")
    op.drop_index(op.f("ix_roles_created_at"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_permissions_last_modified"), table_name="permissions")
    op.drop_index(op.f("ix_permissions_created_at"), table_name="permissions")
    op.drop_table("permissions")
    op.drop_index(op.f("ix_groups_last_modified"), table_name="groups")
    op.drop_index(op.f("ix_groups_created_at"), table_name="groups")
    op.drop_table("groups")
    op.drop_index(op.f("ix_faculties_last_modified"), table_name="faculties")
    op.drop_index(op.f("ix_faculties_created_at"), table_name="faculties")
    op.drop_table("faculties")
    # ### end Alembic commands ###
