"""initial migration

Revision ID: a8774e465100
Revises:
Create Date: 2025-10-16 01:02:17.039988

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a8774e465100"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "faculties",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("uuid", sa.String(length=50), nullable=False),
        sa.Column(
            "date", sa.Date(), server_default=sa.text("CURRENT_DATE"), nullable=True
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "last_modified",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("display_name"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_faculties_created_at"), "faculties", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_faculties_date"), "faculties", ["date"], unique=False)
    op.create_index(
        op.f("ix_faculties_last_modified"), "faculties", ["last_modified"], unique=False
    )
    op.create_table(
        "groups",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("uuid", sa.String(length=50), nullable=False),
        sa.Column(
            "date", sa.Date(), server_default=sa.text("CURRENT_DATE"), nullable=True
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "last_modified",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_groups_created_at"), "groups", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_groups_date"), "groups", ["date"], unique=False)
    op.create_index(
        op.f("ix_groups_last_modified"), "groups", ["last_modified"], unique=False
    )
    op.create_table(
        "permissions",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("uuid", sa.String(length=50), nullable=False),
        sa.Column(
            "date", sa.Date(), server_default=sa.text("CURRENT_DATE"), nullable=True
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "last_modified",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_permissions_created_at"), "permissions", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_permissions_date"), "permissions", ["date"], unique=False)
    op.create_index(
        op.f("ix_permissions_last_modified"),
        "permissions",
        ["last_modified"],
        unique=False,
    )
    op.create_table(
        "roles",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("uuid", sa.String(length=50), nullable=False),
        sa.Column(
            "date", sa.Date(), server_default=sa.text("CURRENT_DATE"), nullable=True
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "last_modified",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_roles_created_at"), "roles", ["created_at"], unique=False)
    op.create_index(op.f("ix_roles_date"), "roles", ["date"], unique=False)
    op.create_index(
        op.f("ix_roles_last_modified"), "roles", ["last_modified"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("old_password_hash", sa.String(length=255), nullable=True),
        sa.Column("temp_password_hash", sa.String(length=255), nullable=True),
        sa.Column("firstname", sa.String(length=255), nullable=False),
        sa.Column("lastname", sa.String(length=255), nullable=False),
        sa.Column("middlename", sa.String(length=255), nullable=True),
        sa.Column("fullname", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_admin", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("can_login", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("is_temp_email", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("is_temp_phone", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("uuid", sa.String(length=50), nullable=False),
        sa.Column(
            "date", sa.Date(), server_default=sa.text("CURRENT_DATE"), nullable=True
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "last_modified",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("phone"),
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_index(op.f("ix_users_date"), "users", ["date"], unique=False)
    op.create_index(
        op.f("ix_users_last_modified"), "users", ["last_modified"], unique=False
    )
    op.create_table(
        "departments",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("faculty_id", sa.String(length=45), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("uuid", sa.String(length=50), nullable=False),
        sa.Column(
            "date", sa.Date(), server_default=sa.text("CURRENT_DATE"), nullable=True
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "last_modified",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["faculty_id"], ["faculties.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("display_name"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_departments_created_at"), "departments", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_departments_date"), "departments", ["date"], unique=False)
    op.create_index(
        op.f("ix_departments_last_modified"),
        "departments",
        ["last_modified"],
        unique=False,
    )
    op.create_table(
        "permission_role",
        sa.Column("permission_id", sa.String(length=50), nullable=True),
        sa.Column("role_id", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.uuid"],
        ),
    )
    op.create_table(
        "role_group",
        sa.Column("role_id", sa.String(length=50), nullable=True),
        sa.Column("group_id", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.uuid"],
        ),
    )
    op.create_table(
        "user_group",
        sa.Column("group_id", sa.String(length=50), nullable=True),
        sa.Column("user_id", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.uuid"],
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_group")
    op.drop_table("role_group")
    op.drop_table("permission_role")
    op.drop_index(op.f("ix_departments_last_modified"), table_name="departments")
    op.drop_index(op.f("ix_departments_date"), table_name="departments")
    op.drop_index(op.f("ix_departments_created_at"), table_name="departments")
    op.drop_table("departments")
    op.drop_index(op.f("ix_users_last_modified"), table_name="users")
    op.drop_index(op.f("ix_users_date"), table_name="users")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_roles_last_modified"), table_name="roles")
    op.drop_index(op.f("ix_roles_date"), table_name="roles")
    op.drop_index(op.f("ix_roles_created_at"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_permissions_last_modified"), table_name="permissions")
    op.drop_index(op.f("ix_permissions_date"), table_name="permissions")
    op.drop_index(op.f("ix_permissions_created_at"), table_name="permissions")
    op.drop_table("permissions")
    op.drop_index(op.f("ix_groups_last_modified"), table_name="groups")
    op.drop_index(op.f("ix_groups_date"), table_name="groups")
    op.drop_index(op.f("ix_groups_created_at"), table_name="groups")
    op.drop_table("groups")
    op.drop_index(op.f("ix_faculties_last_modified"), table_name="faculties")
    op.drop_index(op.f("ix_faculties_date"), table_name="faculties")
    op.drop_index(op.f("ix_faculties_created_at"), table_name="faculties")
    op.drop_table("faculties")
    # ### end Alembic commands ###
